# Documentation Metadata
springdoc.openapi.info.title=Foo Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice handles CRUD operations \
                                   for the Foo domain object.

# Actuator
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${springdoc.openapi.info.title}
info.app.environment=${spring.profiles.active}
