# General
spring.application.name=${SPRING_APP_NAME}

# Documentation
springdoc.openapi.info.title=Demo Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=This microservice handles CRUD operations.
